### ISSUE TITLE
Problem with some hostings that may interrupt downloading

### ISSUE THREAD

**Issue by Bartixxx32** [Stax124/Updater#3]
Hello i have problem with bigger files, the hosting im trying to use seems interrupt download, and that causes program to crash, it would be cool to add it ability to retry or use custom downloader, for example how wget doing it:
![image](https://user-images.githubusercontent.com/16412925/155180534-7dcc9e81-5b75-4b74-a207-346ccf6deb74.png)

Sample wget output:

![image](https://user-images.githubusercontent.com/16412925/155174134-fa3ed8c1-f218-4a72-ab8a-25e87435ddf4.png)

To solution for this may be reopening connection if there was error, or use custom downloader libray

Ps: its 100% not my side fault, its hosting provider, but i think its not hard to workarout this by retry downloading
I have setup a test server for this:

https://testfilebart.netlify.app/hashtable.hash

and the main file 

https://testfilebart.netlify.app/1GB.zip

**Comment by Stax124** [comment]
![Screenshot 2022-02-24 201519](https://user-images.githubusercontent.com/60222162/155591809-eee4bd32-3ac4-4fd2-bf41-183956d23716.png)

On my side, that file is no longer accessible, or it never was. From the error that the updater throw, the second seems more like it. I might do some error handling with better, coloured output.

Try re-uploading that file and give me an update.
(also, please try **curl**-ing it instead of **wget**-ing it)

**Comment by Bartixxx32** [comment]
Maybe my file was removed beouse it was zeros file, this is free static page hosting https://netlify.app

I will try make some garbage file and reporst it to same url as before

**Comment by Stax124** [comment]
Link is still not operational. I will try to add some reconnect algorithm next week, but I can't guarantee that it will work for your use case if I have nothing to test it against.
